version: '3'

services:
  frontend:
    build:
      context: ./docker-frontend
      dockerfile: Dockerfile

    container_name: frontend-nextjs
    working_dir: /frontend
    stop_signal: SIGINT
    volumes:
      - type: bind
        source: /frontend
        target: ./src/frontend
    ports:
      - '3000:3000'
    
    stdin_open: true
    tty: true