version: '3'

services:
  frontend:
    build:
      context: ./docker-frontend
      dockerfile: Dockerfile

    container_name: frontend-nextjs
    working_dir: /frontend
    environment:
      - TZ=Asia/Tokyo
      - PS1=\[\e[34m\]\w\n\[\e[0m\]*\[\e[35m\]\u\[\e[0m\]:\[\e[32m\]\W\[\e[0m\]$ 
    stop_signal: SIGINT
    volumes:
      - type: bind
        source: ./src/frontend
        target: /frontend
    ports:
      - '3000:3000'
    
    stdin_open: true
    tty: true