import Head from 'next/head'
import { Inter } from 'next/font/google'

import { SideBar } from './components/sidebar/SideBar'
import { SidebarType, Size } from './components/sidebar/type'
const inter = Inter({ subsets: ['latin'] })
const testprop = [
  {
    "company_name": "カイシャ1",
    "company_id": "kaisya1",
    "user_id": "mono",
    "recruitment_status": "1"
  },
  {
    "company_name": "カイシャ2",
    "company_id": "kaisya2",
    "user_id": "mono",
    "recruitment_status": "2"
  },
  {
    "company_name": "カイシャ3",
    "company_id": "kaisya3",
    "user_id": "mono",
    "recruitment_status": "3"
  },
  {
    "company_name": "カイシャ4",
    "company_id": "kaisya4",
    "user_id": "mono",
    "recruitment_status": "4"
  }

]

const data = {
  type: 3 as SidebarType,
  size: "s" as Size,
  level: 2,
  adjusting: false,
  reject: false,
  offer: true,
  pass: false,
  fail: false,
  date: new Date("2023-06-17 12:59:38.858725"),
  name: "株式会社採用します",
};
import Button from '@mui/material/Button';

export default function Home() {
  return (
    <>
      <Head>
        <title>就活メモ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <SideBar {...data}
        />
      </div>
    </>
  )
}
