profiles:
  get:
    summary: プロファイルの表示

    tags:
      - profile
      - core

    parameters:
      - in: cookie
        name: session_id
        description: The session
        schema:
          type: string
          format: uuid

      - in: cookie
        name: users_id
        description: ユーザID
        schemas:
          type: string
          format: uuid

    responses:
      "200":
        description: 成功
        content:
          application/json:
          schema:
            oneof:
             - $ref: "../components/schemas/profile.yml#/profile"
             - $ref: "../components/schemas/core.yml#/cores"
      "400":
        $ref: "../components/response/400.yml"
      "401":
        $ref: "../components/response/400.yml"
      "403":
        $ref: "../components/response/400.yml"
      "404":
        $ref: "../components/response/400.yml"
      "422":
        $ref: "../components/response/400.yml"
      "500":
        $ref: "../components/response/400.yml"

  post:
    summary: プロファイルのアップデート
    tags:
      - profile

    requestBody:
      application/json:
      content:
        schema:
          $ref: "../components/schemas/profile.yml#/profile"
    responses:
      "200":
        description: 成功
        content:
          application/json:
          schema:
            $ref: "../components/schemas/profile.yml#/profile"
      "400":
        $ref: "../components/response/400.yml"
      "401":
        $ref: "../components/response/400.yml"
      "403":
        $ref: "../components/response/400.yml"
      "404":
        $ref: "../components/response/400.yml"
      "422":
        $ref: "../components/response/400.yml"
      "500":
        $ref: "../components/response/400.yml"